### ISSUE TITLE
CAFF processor

### ISSUE THREAD

**Issue by verebecske** [erdosadam24/ad-astra-cs-2021#6]
- [x] CIFF -> image logika implementálása (CIFF objektum)
   - public CIFF   -> image
   - public image -> CIFF
   - public formátumellenőrzés (CIFF)

- [x] CAFF -> gif logika implentálása (CAFF objektum)
  - public CAFF -> gif
  - public gif -> CAFF
  - public formátumellenőrzés (CAFF)

**Comment by Vica343** [comment]
CIFF -> kép implementálva 
CAF parser implementálva
